version: 1.0.{build}
image: Visual Studio 2015
clone_folder: c:\gopath\src\github.com\d-led\risgo
environment:
  GOPATH: c:\gopath
build_script:
- cmd: >-
    call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64

    call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

    make.bat